require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/**/*.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/bin/**'
    - 'tmp/**/db/**/*.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/initializers/simple_form_bootstrap.rb
    - config/environments/production.rb
    - config/routes.rb

Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/migrate/*.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb
